---
title: Aetova Architecture
config: 
    theme: dark
    layout: elk
    themeVariables:
        primaryTextColor: '#000'
---
graph LR

    classDef LibColor fill:#880000
    classDef PageColor fill:#008800

    A[Frontend]
    A --> B(Resources)
    B --> BA(Web)
    BA --> BAA(Home)
    BA --> BAB(Shop)
    BA --> BAC(Library)
    BA --> BAD(Installed)
    BA --> BAE(Profile)
    BA --> BAF(Friends)
    BA --> BAG(Default Game Page)
    B --> BB(Assets)
    BB --> BBA(Img)
    BB --> BBB(Icons)
    BB --> BBC(Fonts)
    A --> C(Dependencies)
    C --> CA(docLogger v1.1.1)
    A --> D(Sources)
    D --> DA(Client Bridge)
    D --> DB(View)
    D --> DC(App)
    D --> DD(Process)

    class DA LibColor
    class DB LibColor
    class DC LibColor
    class DD LibColor

    class BAA PageColor
    class BAB PageColor
    class BAC PageColor
    class BAD PageColor
    class BAE PageColor
    class BAF PageColor
    class BAG PageColor

subgraph Lib Legend
    Lib --> include
    Lib --> src
    class Lib LibColor
end

subgraph Pages Legend
    Pages --> View
    Pages --> Style
    Pages --> Script
    class Pages PageColor
end