### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Test)
add_subdirectory(TestContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Testplugin
    TestContentplugin)