FROM golang:1.25.3

ARG PORT

ENV PORT=$PORT

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping

EXPOSE $PORT

CMD [ "/docker-gs-ping" ]